# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-11-27 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stud_info',
            options={'verbose_name': 'Student Information', 'verbose_name_plural': "Student's Information"},
        ),
        migrations.AddField(
            model_name='stud_info',
            name='s_age',
            field=models.IntegerField(default=18, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='stud_info',
            name='s_city',
            field=models.CharField(choices=[('rkt', 'Rajkot'), ('amd', 'Ahmedabad'), ('sur', 'Surat')], default='Rajkot', max_length=50, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='stud_info',
            name='s_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='stud_info',
            name='s_address',
            field=models.CharField(max_length=500, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='stud_info',
            name='s_name',
            field=models.CharField(max_length=264, unique=True, verbose_name='Name'),
        ),
    ]
