# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-11-27 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_auto_20201127_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stud_marks',
            options={'verbose_name': 'Student Result', 'verbose_name_plural': "Student's Result"},
        ),
        migrations.AddField(
            model_name='stud_marks',
            name='s_per',
            field=models.FloatField(default=0, verbose_name='Percentage'),
        ),
        migrations.AddField(
            model_name='stud_marks',
            name='s_total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='stud_marks',
            name='s_marks1',
            field=models.IntegerField(default=0, verbose_name='Django'),
        ),
        migrations.AlterField(
            model_name='stud_marks',
            name='s_marks2',
            field=models.IntegerField(default=0, verbose_name='Ionic'),
        ),
        migrations.AlterField(
            model_name='stud_marks',
            name='s_marks3',
            field=models.IntegerField(default=0, verbose_name='Hadoop'),
        ),
    ]
